Client/VehicleRegister.Client/Controllers/AutoMotiveRegisterController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using VehicleRegister.Client.Helpers;
using VehicleRegister.Domain.DTO.AutoMotiveDTO.Request;
using VehicleRegister.Domain.DTO.AutoMotiveDTO.Response;
using VehicleRegister.Domain.Models.Auth;

namespace VehicleRegister.Client.Controllers
{
    public class AutoMotiveRegisterController : Controller
    {
        public async Task<IActionResult> Index()
        {
            using (var _httpClient = new HttpClient())
            {
                var requestUrl = AutoMotiveRoute.AutoMotives;
                var response = await _httpClient.GetAsync(requestUrl);
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = response.Content.ReadAsStringAsync().Result;
                    var autoMotives = JsonConvert.DeserializeObject<List<GetAllAutoMotivesDto>>(jsonString);
                    return View(autoMotives);
                }
            }
            return RedirectToAction("Index", "Home");
        }



        [HttpGet]
        public async Task<IActionResult> AutoMotiveDetails(int id)
        {
            using (var _httpClient = new HttpClient())
            {
                var requestUrl = AutoMotiveRoute.AutoMotive + id;
                var response = await _httpClient.GetAsync(requestUrl);
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = response.Content.ReadAsStringAsync().Result;
                    var vehicle = JsonConvert.DeserializeObject<GetAutoMotiveDto>(jsonString);
                    return View(vehicle);
                }
            }
            return RedirectToAction("Index", "Home");
        }




        [HttpGet]
        public async Task<IActionResult> UpdateAutoMotive(int? id)
        {
            using (var _httpClient = new HttpClient())
            {
                var requestUrl = AutoMotiveRoute.AutoMotive + id;
                var response = await _httpClient.GetAsync(requestUrl);
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = response.Content.ReadAsStringAsync().Result;
                    var vehicle = JsonConvert.DeserializeObject<UpdateAutoMotiveDto>(jsonString);
                    return View(vehicle);
                }
            }
            return RedirectToAction("Index", "Home");
        }


        [HttpPost]
        public async Task<IActionResult> UpdateAutoMotive(UpdateAutoMotiveDto update)
        {
            if (ModelState.IsValid)
            {
                using (var _httpClient = new HttpClient())
                {
                    var session = SessionHelper.GetObjectFromJson<LoginModel>(HttpContext.Session, "identity");

                    if (session is null) return RedirectToAction("Login", "Account");


                    var updateVehicle = JsonConvert.SerializeObject(update);
                    var content = new StringContent(updateVehicle, Encoding.UTF8, "Application/json");
                    var requestUrl = AutoMotiveRoute.UpdateAutoMotive;
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", session.Token);
                    var response = await _httpClient.PutAsync(requestUrl, content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }





        [HttpGet]
        public IActionResult CreateAutoMotive()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateAutoMotive(CreateAutoMotiveDto request)
        {
            if (ModelState.IsValid)
            {
                using (var _httpClient = new HttpClient())
                {
                    var session = SessionHelper.GetObjectFromJson<LoginModel>(HttpContext.Session, "identity");

                    if (session is null) return RedirectToAction("Login", "Account");


                    var createdAutoMotive = JsonConvert.SerializeObject(request);
                    var content = new StringContent(createdAutoMotive, Encoding.UTF8, "Application/json");
                    var requestUrl = AutoMotiveRoute.CreateAutoMotive;
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", session.Token);
                    var response = await _httpClient.PostAsync(requestUrl, content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index");
                    }
                }
            }
            return View();
        }

    
        [HttpGet]
        public async Task<IActionResult> DeleteAutoMotive(int? id)
        {
            using (var _httpClient = new HttpClient())
            {
                var requestUrl = AutoMotiveRoute.AutoMotive + id;
                var response = await _httpClient.GetAsync(requestUrl);
                if (response.IsSuccessStatusCode)
                {
                    var jsonString = response.Content.ReadAsStringAsync().Result;
                    var vehicle = JsonConvert.DeserializeObject<DeleteAutoMotiveDto>(jsonString);
                    return View(vehicle);
                }
            }
            return View();
        }

        [HttpPost, ActionName("DeleteAutoMotive")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            using (var _httpClient = new HttpClient())
            {
                var session = SessionHelper.GetObjectFromJson<LoginModel>(HttpContext.Session, "identity");

                if (session is null) RedirectToAction("Login", "Account");

                _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", session.Token);
                var requestUrl = AutoMotiveRoute.DeleteAutoMotive + id;
                var response = await _httpClient.DeleteAsync(requestUrl);
                if (response.IsSuccessStatusCode)
                {
                    return RedirectToAction("Index");
                }
            }
            return RedirectToAction("Index", "Home");
        }


    }
}

Client/VehicleRegister.Client/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using VehicleRegister.Client.Helpers;
using VehicleRegister.Domain.DTO.AutoMotiveDTO.Response;
using VehicleRegister.Domain.DTO.ReservationsDTO.Request;
using VehicleRegister.Domain.DTO.VehicleDTO.Response;
using VehicleRegister.Domain.Models.Auth;

namespace VehicleRegister.Client.Controllers
{
    public class ServiceController : Controller
    {
        [HttpGet]
        public async Task<IActionResult> BookService()
        {
           
                var listOfVehicles = new List<GetAllVehiclesDto>();
                var listOfAutoMotives = new List<GetAllAutoMotivesDto>();

                using (var _httpClient = new HttpClient())
                {
                    var requestUrl = VehicleRoute.Vehicles;
                    var response = await _httpClient.GetAsync(requestUrl);
                    if (response.IsSuccessStatusCode)
                    {
                        var jsonString = response.Content.ReadAsStringAsync().Result;
                        listOfVehicles = JsonConvert.DeserializeObject<List<GetAllVehiclesDto>>(jsonString);
                    }

                    var Url = AutoMotiveRoute.AutoMotives;
                    var responsed = await _httpClient.GetAsync(Url);
                    if (responsed.IsSuccessStatusCode)
                    {
                        var jsonString = responsed.Content.ReadAsStringAsync().Result;
                        listOfAutoMotives = JsonConvert.DeserializeObject<List<GetAllAutoMotivesDto>>(jsonString);
                    }
                }

                var vehList = listOfVehicles.Select(c => new SelectListItem()
                {
                    Text = c.RegisterNumber,
                    Value = c.Id.ToString()
                });

                var autoList = listOfAutoMotives.Select(c => new SelectListItem()
                {
                    Text = c.Name,
                    Value = c.Id.ToString()
                });

                ViewBag.Vehicles = vehList;
                ViewBag.AutoMotives = autoList;

                return View();
        }

        [HttpPost]
        public async Task<IActionResult> BookService(ClientCreateReservationDto request)
        {
            if (ModelState.IsValid)
            {
                using (var _httpClient = new HttpClient())
                {
                    var session = SessionHelper.GetObjectFromJson<LoginModel>(HttpContext.Session, "identity");

                    if (session is null) return RedirectToAction("Login", "Account");


                    var createdReservation = JsonConvert.SerializeObject(request);
                    var content = new StringContent(createdReservation, Encoding.UTF8, "Application/json");
                    var requestUrl = ServiceRoute.CreateBooking;
                    _httpClient.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", session.Token);
                    var response = await _httpClient.PostAsync(requestUrl, content);

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("Index", "ServiceHistory");
                    }
                }
            }
            return RedirectToAction("BookService");
        }
    }
}

Client/VehicleRegister.Client/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using VehicleRegister.Client.Helpers;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VehicleRegister</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-black.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    @{ var auth = SessionHelper.GetObjectFromJson<LoginModel>(Context.Session, "identity"); }


    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">
                <img src="~/Images/Logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
                </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="VehicleRegister" asp-action="Index">VehicleRegister</a></li>
                    <li><a asp-controller="AutoMotiveRegister" asp-action="Index">AutoMotives</a></li>

                    @if (auth != null)
                    {
                        @if (auth.IsLoggedIn)
                        {
                            <li><a asp-controller="Service" asp-action="BookService">Book service</a></li>
                            <li><a asp-controller="ServiceHistory" asp-action="Index">Services & History</a></li>
                        }
                    }
                </ul>



                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <partial name="_SearchPartial" />
                    </li>
                    <li>
                        <partial name="_LoginPartial" />
                    </li>
                </ul>
            </div>
        </div>
    </nav>




    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 VehicleRegister - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Client/VehicleRegister.Client/Views/Shared/_SearchPartial.cshtml
@using VehicleRegister.Domain.DTO.VehicleDTO.Response

@{ 
    var search = new VehicleSearch();
}

<ul class="searchInput">
    <li>
        <form asp-controller="VehicleRegister" asp-action="Search" method="post" id="search-form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input asp-for="@search.SearchKeyword" id="search-input" type="text" placeholder="Search ...">
            <button type="submit" class="btn btn-success" id="submit-btn">Search</button>
        </form>
    </li>
</ul>